version: '3.8'

services:
  web:
    build:
      context: .
      platforms:
        - linux/amd64
    platform: linux/amd64
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: "NF@2019"
      MYSQL_DATABASE: ibkmaceio
    volumes:
      - db_data:/var/lib/mysql
      - ./db_ibkmaceio_2025-09-21_2019.sql.gz:/docker-entrypoint-initdb.d/dump.sql.gz
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pNF@2019"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data:
